### ISSUE TITLE
"Symbol loading failed" when trying to use a method with ref struct argument

### ISSUE THREAD

**Issue by Lakritzator** [Firwood-Software/AdvanceDLSupport#29]
### Description
I have successfully used this project for a small test, but I somehow can't seem to get things working when it gets complex.

My use case is mainly to optimize and simplify the usage of Win32 APIs like User32 and Kernel32 etc.

I started with:
```
    public interface IUser32
    {
        /// <summary>
        /// Retrieves a handle to the desktop window. The desktop window covers the entire screen. The desktop window is the area on top of which other windows are painted.
        /// See <a href="https://msdn.microsoft.com/en-us/library/windows/desktop/ms633504(v=vs.85).aspx">GetDesktopWindow function</a>
        /// </summary>
        /// <returns>the return value is a handle to the desktop window.</returns>
        IntPtr GetDesktopWindow();
    }
```
And generate native code with:
```
        public static IUser32 GenerateUser32()
        {
            var activator = new NativeLibraryBuilder(ImplementationOptions.UseIndirectCalls);
            return activator.ActivateInterface<IUser32>("user32");
        }
```
This works, and the performance improvement compated to DllImport (measured with BenchmarkDotNet) is almost 2 fold. This is very cool!

Now I wanted to make the test more complex, using ref / structs, and got into a problem.
The P/Invoke for the example can be found here: https://www.pinvoke.net/default.aspx/kernel32.getversionex

### Repro steps

Please provide the steps required to reproduce the problem

1. Create an interface for the Kernel32 lib
```
    public interface IKernel32
    {
        /// <summary>
        /// See <a href="https://msdn.microsoft.com/en-us/library/windows/desktop/ms724451(v=vs.85).aspx">GetVersionEx function</a>
        /// See also <a href="https://www.pinvoke.net/default.aspx/kernel32.getversionex">pinvoke getversionex</a>
        /// </summary>
        /// <param name="osVersionInfo">ref to OsVersionInfoEx</param>
        /// <returns>bool</returns>
        bool GetVersionEx(ref OsVersionInfoEx osVersionInfo);
    }

 [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
    public struct OsVersionInfoEx
    {
        public int dwOSVersionInfoSize;
        public int dwMajorVersion;
        public int dwMinorVersion;
        public int dwBuildNumber;
        public int dwPlatformId;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)]
        public string szCSDVersion;
        public ushort wServicePackMajor;
        public ushort wServicePackMinor;
        public ushort wSuiteMask;
        public byte wProductType;
        public byte wReserved;
    }

```

2. Generate the native code

```
        public static IKernel32 GenerateKernel32()
        {
            var activator = new NativeLibraryBuilder(ImplementationOptions.UseIndirectCalls);
            return activator.ActivateInterface<IKernel32>("kernel32");
        }
```
3. Call the code

```
            OsVersionInfoEx osVersionInfoEx = new OsVersionInfoEx();
            if (!_kernel32.GetVersionEx(ref osVersionInfoEx))
            {
                throw new NotSupportedException("Whaaaat?");
            }
```

### Expected behavior

No exception, and the structure osVersionInfoEx should be filled.

### Actual behavior

I get an exception:

System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> AdvancedDLSupport.SymbolLoadingException: Symbol loading failed. Symbol name: GetVersionEx ---> System.ComponentModel.
Win32Exception: Die angegebene Prozedur wurde nicht gefunden (The supplied function was not found)
   bei AdvancedDLSupport.NativeLibraryBuilder.ActivateClass[TClass,TInterface](String libraryPath)
   bei AdvancedDLSupport.NativeLibraryBuilder.ActivateInterface[TInterface](String libraryPath)

### Related information 

* Operating system - Windows 7 & Windows 10
* What version of the library - NuGet v1.2.2
* What runtime - .NET Framework 4.7
* Workarounds - None known

Any tipps & hints? I probably overlooked something..

**Comment by Nihlus** [comment]
Does it work if you use the delegate backend instead of the `calli` backend? As far as I can tell, you're doing things correctly, however, according to the documentation, `GetVersionEx` is deprecated and may not be available after Windows 8.1 (see [GetVersionEx][versionex]). 

Instead, according to MSDN, the [Version Helper Functions][versionhelp] should be used instead.

I'd also like to warn you that structs with embedded managed types like strings might not behave as expected when using `calli` - one part of what makes `calli` so much faster is that it doesn't do any marshalling on its own. ADL does perform some marshalling itself, so the library-provided features will work, but things like MarshalAs may not.

[versionex]: https://msdn.microsoft.com/en-us/library/windows/desktop/ms724451(v=vs.85).aspx
[versionhelp]: https://msdn.microsoft.com/en-us/library/windows/desktop/dn424972(v=vs.85).aspx

**Comment by Lakritzator** [comment]
I tried user32.GetPhysicalCursorPos, which uses an **out**, this seems to work just fine.
I will find another function with a ref to a struct to make sure this is not a ref issue.
And also test a simple one with Kernel32, to make sure it's not that library.

P.S.
The call GetPhysicalCursorPos itself is very slow, so the performance win is almost neglect-able :cry: 

Method | Mean | Error | StdDev | Min | Max | Allocated
-- | -- | -- | -- | -- | -- | --
GetDesktopWindowAdvancedDlSu | 9.547 ns | 0.0127 ns | 0.0112 ns | 9.519 ns | 9.560 ns | 0 B
GetDesktopWindowDllImport | 18.828 ns | 0.0352 ns | 0.0329 ns | 18.775 ns | 18.889 ns | 0 B
GetPhysicalCursorPosAdvanceDlSu | 681.407 ns | 1.9482 ns | 1.8224 ns | 678.743 ns | 684.997 ns | 0 B
GetPhysicalCursorPosDllImport | 684.055 ns | 1.9673 ns | 1.8402 ns | 680.117 ns | 686.618 ns | 0 B

**Comment by Nihlus** [comment]
It may also be a matter of the charset used - some system calls are suffixed by their respective charset identifiers - try adding that explicitly.

**Comment by Nihlus** [comment]
I'll write up some docs that clarify what's supported under `calli` as well :)

**Comment by Nihlus** [comment]
Actually, here's something from the pinvoke site that may be relevant: 

Tips & Tricks:
If you forget to set the OSVersionInfoSize field of the OSVERSIONINFO struct, the function will return false. GetLastError() will return:

127

ERROR_PROC_NOT_FOUND

"The specified procedure could not be found."

**Comment by Lakritzator** [comment]
Yeah you are right, actually I initialise my struct differently as the example (one should not optimise their example to much) but it's definitively set!

`dwOSVersionInfoSize = Marshal.SizeOf(typeof(OsVersionInfoEx))`

The error is in the ActivateInterface, not the actually calling of the resulting interface.

**Comment by Lakritzator** [comment]
That other information was good, thanks!

The error was with the Charset, I should have specified `GetVersionExW`!
Now the call works, I still have to check the result but there is no exception.

I should have known this, but it's something I am used to so much, that I forgot that A/W are added depending on the charset. Having an interface with such Method-Names is somewhat sobering, is there a way to make an interface method to a different name?

P.S.
For this example, the AdvanceDLSupport call seems to be a lot slower.

**Comment by Lakritzator** [comment]
FYI to everybody who is interested in the "answer":

So after rebuilding the issue is away, and with the EntryPoint things are working fine.
```
        [NativeSymbol("GetVersionExW")]
        bool GetVersionEx(ref OsVersionInfoEx osVersionInfo);
```

With the GetVersionEx example, here is the benchmarking for the performance difference between DllImport and AdvanceDLSupport:

Method | Mean | Error | StdDev | Min | Max | Allocated
-- | -- | -- | -- | -- | -- | --
GetVersionExAdvanceDiSu | 634.2 ns | 0.8390 ns | 0.7848 ns | 632.4 ns | 635.5 ns | 56 B
GetVersionExDllImport | 638.8 ns | 1.0893 ns | 1.0190 ns | 637.4 ns | 640.6 ns | 56 B

One can recognize that the "PInvoke" overhead is reduced (in my case by 4.6ns), in this case there is only a small gain. (as was expected)

> I'd also like to warn you that structs with embedded managed types like strings might not behave as expected when using calli - one part of what makes calli so much faster is that it doesn't do any marshalling on its own. ADL does perform some marshalling itself, so the library-provided features will work, but things like MarshalAs may not.

First I don't really understand why things are working, except the "may not" is just that.. It does work.

But due to your remark, I invested some time to check what other options I had.

In our example case I modified the OsVersionInfoEx struct to use a "fixed char" (which does mean I needed to allow unsafe code).

This is how it looked after the change:

```
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public unsafe struct OsVersionInfoEx
    {
        public int dwOSVersionInfoSize;
        public int dwMajorVersion;
        public int dwMinorVersion;
        public int dwBuildNumber;
        public int dwPlatformId;
        public fixed char szCSDVersion[128];

        public ushort wServicePackMajor;
        public ushort wServicePackMinor;
        public ushort wSuiteMask;
        public byte wProductType;
        public byte wReserved;

        /// <summary>
        /// Factory for an empty OsVersionInfoEx
        /// </summary>
        /// <returns></returns>
        public static OsVersionInfoEx Create()
        {
            int size = Marshal.SizeOf(typeof(OsVersionInfoEx));
            return new OsVersionInfoEx
            {
                dwOSVersionInfoSize = size
            };
        }
    }
```

As I don't need the string, when I do I could convert it, the benchmarking was a surprise to me (but understandable, just never thought about it):

Method | Mean | Error | StdDev | Min | Max | Allocated
-- | -- | -- | -- | -- | -- | --
GetVersionExAdvanceDiSu | 38.26 ns | 0.2828 ns | 0.2645 ns | 37.88 ns | 38.52 ns | 0 B
GetVersionExDllImport | 58.61 ns | 0.4087 ns | 0.3823 ns | 58.15 ns | 59.33 ns | 0 B

Just by changing the structure, it's a lot faster (>16x for your lib), and there are no allocation, this not only is the case for your library but also applies to DllImport (>10x). And I think that with the new Span<T> API it's probably not so hard to use the string if I still need it... but that's another discussion.

Thanks for the support,

**Comment by Lakritzator** [comment]
FYI
When converting the fixed char[128] to string myself (easiest is new string(osVersionInfoEx.szCSDVersion)) the performance is around 6x faster as with a mashal conversion:

Method | Mean | Error | StdDev | Min | Max | Allocated
-- | -- | -- | -- | -- | -- | --
GetVersionExAdvanceDiSu | 80.05 ns | 0.2223 ns | 0.2079 ns | 79.74 ns | 80.53 ns | 56 B
GetVersionExDllImport | 106.19 ns | 0.3179 ns | 0.2482 ns | 105.76 ns | 106.78 ns | 56 B

**Comment by Nihlus** [comment]
Awesome! Glad everything worked out. I'm surprised that the embedded MarshalAs worked - I'll have to investigate that.

**Comment by Lakritzator** [comment]
I am guessing that this works at the moment of creating the struct instance, when new OsVersionInfoEx() is called. And your code just becomes an constructed struct, which is already in the correct size.

Why I guess this: the Marshal.SizeOf gives the size correctly (with the 128 chars), but a string reference should only be a few bytes. How this actually works, is a good question... and why the additional overhead is ~500ns for my PC, is also a good question :smile:

**Comment by Nihlus** [comment]
That sounds like a plausible explanation- interesting!
