### ISSUE TITLE
Introduce Fody to do everything you do right now, but at compile time

### ISSUE THREAD

**Issue by Lakritzator** [Firwood-Software/AdvanceDLSupport#31]
No error, just an idea for your "roadmap":
Currently the code is generated at runtime, I myself don't have a reason for that and it feels to me like it would be more logical if the code is generated as part of the build. This should be possible by using https://github.com/Fody/Fody

I am considering this myself, for a library I wrote. It should make the library usable on most platforms, as code generation at runtime is an issue for some of them.

Maybe there are use cases which I don't know of, just felt like discussing this with you.

P.S.
There is also a Pluralsight course for it, if you happen to be a member:
https://app.pluralsight.com/library/courses/automatic-dotnet-code-weaving-fody/table-of-contents
Although it's a bit older...

**Comment by Nihlus** [comment]
I might have a look at that some time - at present, you can generate the code as a part of your build and simply load the cached types at runtime. See https://firwood-software.github.io/AdvanceDLSupport/ahead-of-time.html for more info.

**Comment by Nihlus** [comment]
Because of Fody's recent licensing update, this is unlikely to happen.
