### ISSUE TITLE
Potential error in GetUniqueBaseMemberName() implementation

### ISSUE THREAD

**Issue by TGEnigma** [Firwood-Software/AdvanceDLSupport#38]
It seems that GetUniqueBaseMemberName() at:
https://github.com/Firwood-Software/AdvanceDLSupport/blob/1b7394211a655b2f77649ce3b610a3161215cbdc/AdvancedDLSupport/Pipeline/PipelineWorkUnit.cs#L86

creates a new GUID every time it is called, making subsequent invocations return different values. 
Is this the intended behaviour?

**Comment by Nihlus** [comment]
Yes, this is the intended behaviour. It's an internally unique member name, and isn't intended to be exposed to the end user. With a little work, I'm sure it could be made more deterministic, but it's not a priority. 

The main issue I ran into was duplicate member names in inheriting classes, as I recall, or something in the same vein. Might have another look in the future.

**Comment by TGEnigma** [comment]
Thanks for the clarification.
