### ISSUE TITLE
dylib not found on Mac.

### ISSUE THREAD

**Issue by pauldotknopf** [Firwood-Software/AdvanceDLSupport#39]
### Description

The dylib isn't found, even with `DYLD_LIBRARY_PATH` set correctly.

### Repro steps

```c#
const string myLibraryName = "libQtNetCoreQml"; // or libQtNetCoreQml.dylib or QtNetCoreQml
var activator = new NativeLibraryBuilder();
var library = activator.ActivateInterface<IMyNativeLibrary>(myLibraryName);
```

### Expected behavior

Expected it to find the library.

### Actual behavior

It didn't.

### Related information 

I am using `dotnet` version `2.1.301` on OSX.

I did a little debugging and found the culprit. See here:

https://github.com/Firwood-Software/AdvanceDLSupport/blob/93201d655195279a65e2c0952099bc7f93e02b9b/AdvancedDLSupport/PathResolvers/MacOSPathResolver.cs#L55

The `Path.Combine` results in a valid path, but the `Path.GetFullPath` appends that current path to the working directory. So, it is checking if a file exists at `/current-working-dir//some-path-in-ld/file.dylib` when it should really be checking for a file at`/some-path-in-ld/file.dylib`.

**Comment by pauldotknopf** [comment]
Turns out my `DYLD_LIBRARY_PATH` environment variable had some weird characters in it, like a hidden BOM or something, idk. It was causing strings to be formatted all weird.

**Comment by Nihlus** [comment]
No other issues, I hope?

**Comment by pauldotknopf** [comment]
Nope!

I did notice some types were missing in the NuGet package though. Old release (1.3.0)? I was looking for `CallerFree` and `NativeSymbols` for the interface (not method).

**Comment by pauldotknopf** [comment]
By the way, this library is going to be used in my .NET Core Qml bindings: https://github.com/pauldotknopf/net-core-qml/blob/4c03eca86c9630a8e5488808bd4ed03066f4885a/src/net/Qt.NetCore/Interop.cs

Thanks a lot for this awesome little project!

**Comment by Nihlus** [comment]
I'll see if I've forgotten to update the nuget package. Great to see a project using ADL :D

**Comment by Nihlus** [comment]
The nuget package was outdated, yeah - I've updated it to the latest master branch :)
