### ISSUE TITLE
Can't bind an interface that is internal.

### ISSUE THREAD

**Issue by pauldotknopf** [Firwood-Software/AdvanceDLSupport#40]
It makes sense. But maybe you know some magic?

    TypeLoadException: Type 'CallbacksIterop_a1fefae9_927a_498b_af14_5c370ec8783d' from assembly 'DLSupportDynamicAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is attempting to implement an inaccessible interface.

```c#
internal interface IQGuiApplicationInterop
{
    [NativeSymbol(Entrypoint = "qguiapplication_create")]
    IntPtr Create();
}
```

I'd like to prevent people from poking at my guts.

**Comment by Nihlus** [comment]
Maybe. I looked at it in the past, and I might be able to work around this by making the output assembly name more deterministic - that way, you coud decorate your main assembly with an InternalsVisibleTo attribute... I'll look into it.

**Comment by pauldotknopf** [comment]
The would be great!

**Comment by Nihlus** [comment]
Actually, try this - internally, the dynamic assembly is deterministically named "DLSupportDynamicAssembly", so that should work.

Annotate your assembly with 
```cs
[assembly: InternalsVisibleTo("DLSupportDynamicAssembly")]
```

and see how that goes.

**Comment by pauldotknopf** [comment]
That worked! Thanks a lot!

**Comment by Nihlus** [comment]
Awesome :+1: I'll close the issue for now, but I'll make sure to add this to the docs.
