### ISSUE TITLE
Finding native libraries that are packed into NuGet packages?

### ISSUE THREAD

**Issue by pauldotknopf** [Firwood-Software/AdvanceDLSupport#42]
Title says it all.

For example, libuv:

![image](https://user-images.githubusercontent.com/523150/43372472-453d8f56-936f-11e8-9fcc-af3de349bf0d.png)

What are your thoughts on this? I'd like to wrap up my lib to be used as a clean/pure NuGet package with no native compilation required.

**Comment by Nihlus** [comment]
You can implement and provide your own native library resolver - that should suffice for this use case. It can do any arbitrary lookups for the library path based on the provided library name. Check https://github.com/Firwood-Software/AdvanceDLSupport/tree/master/AdvancedDLSupport/PathResolvers for some examples. 

In fact, it's probably worth PR'ing if you do put one together - I'd love to bundle something like that with the library.

**Comment by pauldotknopf** [comment]
I think I know a trick to support this.

1. Add a library path searcher that generates code that uses DllImport with the requested lib name. Make the method your attempting to import random, doesn't matter.
2. Invoke the method. Check if it loaded, but couldn't find the exported name.
3. If it loaded, inspect the current process for loaded modules to get the path of the dll that was loaded.

What do you think?

**Comment by pauldotknopf** [comment]
```DynamicLinkLibraryPathResolver``` is marked as internal. How do I append to the current resolver functionality, instead of overwriting it completely?

**Comment by Nihlus** [comment]
Appending to the current functionality is not possible at the moment. Exposing it as public is an option we could explore. 

I'm not really seeing how using the DllImport trick would help - the default loader mimics the mechanism DllImport uses, and if that fails, passes it on to the system which does its own thing. 

If the nuget package is configured to copy the built binaries to the program's folder, it'll suffice to have a local-first scan, and then a scan in the nuget package cache.

**Comment by pauldotknopf** [comment]
> If the nuget package is configured to copy the built binaries

It doesn't. It leaves the library in the ".nuget" folder and DllImport auto finds the dll that is located in the appropriate runtime folder.

**Comment by Nihlus** [comment]
Then that's the behaviour we should replicate. I wonder if there's any
source code for that.

**Comment by pauldotknopf** [comment]
I've looked. Everywhere. I have no clue who is responsible for doing that magic.

**Comment by Nihlus** [comment]
I'll have a look around, too. If we can't find anything, we'll just have to
roll our own implementation :)

**Comment by pauldotknopf** [comment]
Take a look at this: https://github.com/pauldotknopf/Qml.Net/blob/windows-static/src/net/Qml.Net/Internal/DllImportLibraryPathResolver.cs

And this: https://github.com/pauldotknopf/Qml.Net/blob/windows-static/src/net/Qml.Net/Internal/Interop.cs#L22

PS: If you let the runtime do it with this magic Reflection.Emit/DllImport stuff, you can let Mono also handle the .dll map stuff.

**Comment by Nihlus** [comment]
Ah, cool! I'll have a look. 

In regards to DllMap, yeah, but then it doesn't work on Core or FX. Better to have one unified implementation.

**Comment by Nihlus** [comment]
Oh, that's great! Since it's relevant for the other platforms as well, putting it in the Linux-specific resolver isn't the best idea - best we put it in DynamicLinkLibraryPathResolver instead.
