### ISSUE TITLE
Clarification on strings and how they are free'd?

### ISSUE THREAD

**Issue by pauldotknopf** [Firwood-Software/AdvanceDLSupport#43]
Consider this line of code.

```c++
Q_DECL_EXPORT LPCSTR qt_getenv(LPCSTR name)
{
    QByteArray result = qgetenv(name);
    if(result.isNull()) {
        return nullptr;
    }
    char* resultString = new char[static_cast<rsize_t>(result.size() + 1)];
    strcpy_s(resultString, static_cast<rsize_t>(result.size() + 1), result.data());
    return resultString;
}
```

```c#
internal interface IQtInterop
{
    [NativeSymbol(Entrypoint = "qt_putenv")]
    bool PutEnv([MarshalAs(UnmanagedType.LPStr)]string name [MarshalAs(UnmanagedType.LPStr)]string value);
    [NativeSymbol(Entrypoint = "qt_getenv")]
    [return: MarshalAs(UnmanagedType.LPStr)]string GetEnv(string name);
}
```

Who is going to delete the buffer returned from ```qt_getenv```? Also, if null (```IntPtr.Zero```) is returned, I assume that the free'in stuff doesn't happen?

**Comment by Nihlus** [comment]
In this case, no freeing is performed by ADL. You must expose a free function yourself, since it has no concept of what kind of memory that pointer is pointing to.

ADL can free unmanaged memory that it creates to pass things to unmanaged code using the CallerFree attribute - however, it doesn't know how to free pointers it receives from unmanaged code. They could have been malloc'ed, AllocHGlobal'ed, etc.

**Comment by Nihlus** [comment]
Actually, no, I forgot - for strings, you can annotate the return parameter with CallerFree, and it will free the pointer.

https://github.com/Firwood-Software/AdvanceDLSupport/blob/master/AdvancedDLSupport/ImplementationGenerators/Wrappers/StringMarshallingWrapper.cs#L260

**Comment by pauldotknopf** [comment]
How would you recommend returning strings?

What about a wrapping struct that contants the buffer and a size? Then we can use .NETs ability to free IntPtr?

**Comment by pauldotknopf** [comment]
Ah, I saw your update.

What method do you use for free? How should I alloc?

**Comment by pauldotknopf** [comment]
Nm, I see it: https://github.com/Firwood-Software/AdvanceDLSupport/blob/master/AdvancedDLSupport/ImplementationGenerators/Wrappers/StringMarshallingWrapper.cs#L406

**Comment by Nihlus** [comment]
I suspect it's because you're in a C++ context, and you've initialized your pointer with an array on the heap - ADL doesn't know how to free a C++ object pointer, and it assumes that the pointer is a HGlobal pointer (malloc or equivalent).

I'm confusing myself a lot here, and ADL can actually free any C-style pointer it gets from unmanaged code, however, it doesn't treat C++ pointers (which are structurally different in terms of freeing logic) any differently - thus, kaboom.

**Comment by pauldotknopf** [comment]
I changed the C++ code to this, still happens:

```c++
Q_DECL_EXPORT LPCSTR qt_getenv(LPCSTR name)
{
    QByteArray result = qgetenv(name);
    if(result.isNull()) {
        return nullptr;
    }
    size_t size = static_cast<size_t>(result.size() + 1);
    char* resultString = static_cast<char*>(malloc(size));
    memcpy(resultString, result.data(), static_cast<size_t>(result.size() + 1));
    return resultString;
}
```

**Comment by pauldotknopf** [comment]
Also, I just noticed a memory leak when sending _in_ strings. Looks like I have to use ```CallerFree``` at all times, and the memory leak goes away.

```c#
[NativeSymbol(Entrypoint = "qt_putenv")]
        bool PutEnv([MarshalAs(UnmanagedType.LPStr), CallerFree]string name, [MarshalAs(UnmanagedType.LPStr), CallerFree]string value)
```
Should ```CallerFree``` be default for input strings?

**Comment by pauldotknopf** [comment]
I'm considering just adding this type for all transferring of strings.

```c#
[StructLayout(LayoutKind.Sequential)]
public struct StringContainer
{
    IntPtr Data
    int Size
}
```

Then, add an export that managed code can call to free it. Then I can ensure the proper new/delete/malloc/free get's called for strings.

**Comment by Nihlus** [comment]
Making CallerFree default for input strings might be worth exploring, but that also required an opt-out attribute. Not too hard, but a bit of added complexity. The current behaviour is the intended one.

I'm really not sure why your program is crashing - it's mostly equivalent to what I'm doing in the integration tests, and that works fine:

```c#
__declspec(dllexport) LPCSTR GetString()
{
    return "Hello from C!";
}

__declspec(dllexport) LPCSTR GetAllocatedString()
{
    char* ptr = malloc(strlen(GetString()) + 1);
    strcpy(ptr, GetString());

    return ptr;
}
```

**Comment by pauldotknopf** [comment]
Your returning a const that's compiled in.

Try to make your tests return a deletable char*.

**Comment by pauldotknopf** [comment]
You should get exceptions trying to delete that const char*.

**Comment by Nihlus** [comment]
I'm referring to the "GetAllocatedString" function, which takes a copy of the constant string - the constant string is not freed.

**Comment by pauldotknopf** [comment]
This crashed as well.

```c++
char* ptr = (char*)malloc(strlen("test") + 1);
strcpy(ptr, "test");
return ptr;
```

I'm using VC++ 2017.

My malloc is defined in ```C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\ucrt\corecrt_malloc.h```.

**Comment by Nihlus** [comment]
I've got no idea, sorry. The unit tests are passing on Windows using the VS2017 compiler - perhaps it's because it's compiled for C++? It's always been a problematic language to interop with.

**Comment by pauldotknopf** [comment]
I tried this as well:

```c++
Q_DECL_EXPORT void* qt_getenv(LPCSTR name)
{
    return malloc(10);
}
```

```c#
[NativeSymbol(Entrypoint = "qt_getenv")]
IntPtr GetEnv(string name);
```

Then I free the ```IntPtr``` manually using ```Marshal.FreeHGlobal``` and it still crashed.

There is something deeper that is wrong.

**Comment by pauldotknopf** [comment]
The documentation for ```FreeHGlobal``` says it uses ```LocalFree```.

https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.marshal.freehglobal(v=vs.110).aspx

Does that mean that I _have_ to allocate using ```LocalAlloc```?

I wonder how cross platform that is?

**Comment by pauldotknopf** [comment]
I wonder if your C++ headers in your VS install is ```#define``` malloc to internally use ```LocalAlloc```?

**Comment by Nihlus** [comment]
Possibly - I'm using the one provided by AppVeyor. I don't have a Windows comp myself, so all the Windows tests run there.

**Comment by Nihlus** [comment]
Glad you found it! This has me thinking that building an internal class that wraps the various freeing functions out there isn't a bad idea, and exposing which one to use as an option on CallerFree.

**Comment by pauldotknopf** [comment]
I've tried all the ```Marshal.Free*``` methods, none of them would free the pointer from ```malloc```.

**Comment by Nihlus** [comment]
Yeah, it'd have to load the actual C-style `free` function. Windows has so many ways of allocating memory...

**Comment by BlackCentipede** [comment]
Yeah, you pretty much have to import `msvcrt.dll` library to get that `free` function definition. Malloc/calloc/free contains the information that were internally managed on pages of memories so free would know how much memory exactly needs to be freed.

https://stackoverflow.com/questions/1518711/how-does-free-know-how-much-to-free

**Comment by Nihlus** [comment]
Feel free to open feature request issues for the discussed additions above :)
