### ISSUE TITLE
"AdvancedDLSupport.ExternalAnnotations.xml" file get's put into every project.

### ISSUE THREAD

**Issue by pauldotknopf** [Firwood-Software/AdvanceDLSupport#44]
Can we remove it? I'm not sure why NuGet wants to add it into every project that uses this AdvanceDLSupport.

**Comment by Nihlus** [comment]
That file is a supporting file for R#'s annotation support - nullability, contracts, etc. It avoids having to reference the full package and passing that reference on to library consumers.

**Comment by pauldotknopf** [comment]
Annotation support? Link?

**Comment by pauldotknopf** [comment]
Ah, I see.

The problem is that this is added to every project, even if the reference is transient.

If someone adds a reference to Qml.Net, I don't want them seeing files that they'll never have to touch/use, considering this library is used internally.

**Comment by Nihlus** [comment]
Adding the reference means that that dependency will leak to your users. The file is opaque and isn't "user serviceable", so to speak. 

You can manually exclude it from your nuget package. I'll see if I can improve the inclusion logic, but the current behaviour is intended.

**Comment by pauldotknopf** [comment]
Having these files in every project that reference my ```Qml.Net``` library isn't acceptable.

![image](https://user-images.githubusercontent.com/523150/43559216-26971f40-95db-11e8-909a-e327598fe4c9.png)

This library is an implementation detail, not a framework.

**Comment by Nihlus** [comment]
Ah, now I see what you mean. I wasn't aware that it was visible in the project view - I thought you were referring to the file as a whole. 

Yes, that's not intended. I'll have a look.

**Comment by Nihlus** [comment]
Fixed in 7f57e42.

**Comment by Nihlus** [comment]
A new version of the library will be up on nuget momentarily.
