### ISSUE TITLE
Support for loading exported symbols from main executable.

### ISSUE THREAD

**Issue by pauldotknopf** [Firwood-Software/AdvanceDLSupport#50]
I'd like to host a .NET Core runtime inside of a native C++ executable. My main exe exports some symbols.

I'd like this project to be able to load symbols from the main executable.

I'd understand not having first-class support for this, but maybe consider making things public instead of internal, particularly this: 

https://github.com/Firwood-Software/AdvanceDLSupport/blob/e3d5ce6485a269712e00e0a19bd2dbc8ec4b5d76/AdvancedDLSupport/NativeLibraryBase.cs#L54

Then, I could provide my own ```IPlatformLoader``` that does this.

**Comment by Nihlus** [comment]
Mono supports a special library name for this - `__Internal` - that instructs the runtime to scan the main executable. It shouldn't be too much trouble to let all runtimes have this behaviour.

Allowing the platform loader to be replacable is something I've wanted for a while. I haven't had time to do it yet, though.

I've created a small patch for this at #51 - could you give it a go and see if it does what you want?

**Comment by Nihlus** [comment]
I've released the patch onto NuGet in the latest release.
