### ISSUE TITLE
Implementation of less accessible types

### ISSUE THREAD

**Issue by jvbsl** [Firwood-Software/AdvanceDLSupport#60]
**Is your feature request related to a problem? Please describe.**
```
internal interface IA
{
   void DoStuff();
}
public abstract class X : NativeLibraryBase, IA
{
...
}
```

In my opinion it should create an implementation like that:
```
public class X_asdf : X
{
   void IA.DoStuff()
   {
   }
}
```
while it does create more of something like this:
```
public class X_asdf : X
{
   public void DoStuff()
   {
   }
}
```
**Describe the solution you'd like**
First we should rename the functions to [InterfaceName].[MethodName] for all types with less accessibility for consistency sake(with C#, IL itself can be named like you want afaik):
https://github.com/Firwood-Software/AdvanceDLSupport/blob/master/AdvancedDLSupport/Pipeline/ImplementationPipeline.cs#L202

Secondly this one should use "Private" instead of "Public" Flag for all types with less accessibility:
https://github.com/Firwood-Software/AdvanceDLSupport/blob/master/AdvancedDLSupport/Pipeline/ImplementationPipeline.cs#L203

I noticed this one because in OpenTK some interfaces are internal while in my opinion should be public.

**Comment by Nihlus** [comment]
I'm not sure I follow. If an interface is internal, that's what restricts the use of the methods on the generated implementation (unless you use reflection in which case all bets are off).

Your example shows an explicit interface implementation. Is that what you meant?

**Comment by jvbsl** [comment]
Yeah that's exactly what I meant, sorry I thought I used "explicit" somewhere seems I did not. I mean could be that the abstract class X somehow uses the explicit implementation. I currently do not need it though. It's just something I noticed

**Comment by Nihlus** [comment]
I don't really see a reason for this, since the nature of the system only
exposes the constructed methods via the interface or as a member in an
abstract class inherited by the user.

Do you have any use case examples?

**Comment by jvbsl** [comment]
the only reason I can think of is, if you have a native method which you don't want to expose directly and instead want to use a wrapping function for...e.g. WinAPI:
```
internal IWindowNative
{
   GetWindowTextLengthW(HWND hwnd);
   GetWindowTextW(HWND hwnd, [MarshalAs(LWPSTR)] char* text, int nMaxCount);
}
```
But you actually just want to expose something like that
```
public interface IWindow
{
string GetWindowText(HWND hwnd);
}
public abstract class Window : IWindow, IWindowNative
{
   public unsafe string GetWindowText(HWND hwnd)
   {
      int cnt = GetWindowTextLengthA(hwnd);
      var str = new string('\0', cnt);
      fixed(char* ptr = str)
      {
           GetWindowText(hwnd,ptr,cnt);
      }
      return str;
   }
}
```

It's more or less pseudo code and not real functional(at least I did not try it). Apart from that I don't even now if AdvancedDLSupport tries to overwrite the "string GetWindowText(HWND hwnd)" function or not.

**Comment by Nihlus** [comment]
That sort of thing is completely doable - check the docs for mixed-mode
classes.

Internal behaviour should be defined in internal interfaces, and public
behaviour in public interfaces.

**Comment by jvbsl** [comment]
Are you sure? Because in your current al-adl branch of OpenTK if I update AdvanceDLSupport to the newest nuget version it emits the IL-Code for ALContext successfully, but it can't be instantiated, because the interfaces are internal:
System.TypeInitializationException: The type initializer for 'OpenTK.OpenAL.AudioContext' threw an exception. ---> System.TypeLoadException: Type 'Generated_ALContext_ee68b62d_ab43_40ff_8398_be41f8643e64' from assembly 'DLSupportDynamicAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is attempting to implement an inaccessible interface.
Which does make sense, because they don't get explicitely implemented, but implicitly. Therefore it only works after changing the interfaces to public(which in this case actually does make more sense in my opinion).

**Comment by Nihlus** [comment]
You'll need to annotate your assembly as having its internals visible to ADL's dynamic assembly. Check this issue for how to do that - I thought I'd added it to the wiki, but apparently not. https://github.com/Firwood-Software/AdvanceDLSupport/issues/40

**Comment by jvbsl** [comment]
Ohh okay thanks, I thought it would need to be made private as well to be considered as explicit implementation, but I'm not that well informed on ECMA-335

**Comment by Nihlus** [comment]
I'm closing this issue for now. If a use case comes around, I'll be happy to take another look :)
