### ISSUE TITLE
Calls to native code silently fail when using inherited interfaces.

### ISSUE THREAD

**Issue by pauldotknopf** [Firwood-Software/AdvanceDLSupport#65]
It's hard to describe, and I can't reproduce it in a minimal example. Maybe if I describe it, something will light up.

To begin with, this only happens after upgrading to version ```2.3.0```.

What I'm seeing is that some methods are calling native code, while some methods are ignoring native code completely. But, it only happens when I have a parent interface that implements a bunch of other interfaces.

See the ```ICombined``` inteface [here](https://github.com/qmlnet/qmlnet/blob/8de97f6f64d600eb651642799b214d1b44f029ca/src/net/Qml.Net/Internal/Interop.cs#L133), and it's usage [here](https://github.com/qmlnet/qmlnet/blob/8de97f6f64d600eb651642799b214d1b44f029ca/src/net/Qml.Net/Internal/Interop.cs#L83).

If I manually build one of the child interfaces, the call to native works as expected.

```c#
// This works
builder.ActivateInterface<INetVariantListInterop>("QmlNet").Create()
// This doesn't work
((INetVariantListInterop)builder.ActivateInterface<ICombined>("QmlNet")).Create()
```

I'm using .NET Core 2.1.500 on Linux.

**Comment by Nihlus** [comment]
Without a reproducible example, this will be very hard to nail down - much less fix. Something you could do is pull the source code and run a `git bisect` to track down the specific commit where the problem was introduced.

I did note that you're disabling an ambiguity warning in your interface - are the methods mentioned involved with that warning? If so, I'd say that's a good place to start.

**Comment by pauldotknopf** [comment]
I've identified the specific commit the causes it to happen.

It's this one: https://github.com/Firwood-Software/AdvanceDLSupport/commit/8ad1027cd98d2de3edba389ceefdfce18e2267da

**Comment by pauldotknopf** [comment]
In my attempts to create a minimal reproduction, I didn't try to create an interface that contains similar method signatures/method names. Maybe that is how it can be reproduced. The method that is causing me issues indeed duplicated.

**Comment by Nihlus** [comment]
I've created a unit test with an interface composed of two other interfaces with identical signatures, but I'm still unable to reproduce. Ideas?

**Comment by pauldotknopf** [comment]
I tried to create a minimal repro as well, and couldn't. I'd suggest trying Qml.Net at [this](https://github.com/qmlnet/qmlnet/commit/35634c9f2a6fa9547b96ec2a3b54a4b2b3536749) commit.

First things first, get the unit tests working.

1. Use Qt Creator to build the native ```QmlNet.pro``` project. Use Qt 5.11.X.
2. Update ```Interop.cs``` to set ```LD_LIBRARY_PATH``` (or w/e for your OS) before the lib is loaded.
3. Run ```dotnet test``` on the ```Qml.Net.Tests``` project.

Now, update ADL, and the unit tests will fail.

Every unit test runs through [this](https://github.com/qmlnet/qmlnet/blob/8e1f0cbfe3ed5f69c8f5f5311fbfc6a995a98a0c/src/net/Qml.Net/QGuiApplication.cs#L118) before anything, and you'll see it fail first there. Look at the ```NetVariant``` and ```NetVariantList``` types. The ```Create``` methods don't call the correct ```net_variant_create``` or ```net_variant_list_create``` methods. I suspect it is actually using another ```Create``` method, calling a constructor for some unknown type.

**Comment by pauldotknopf** [comment]
The same issue is present.

I have the project setup if you want to TeamViewer.

**Comment by pauldotknopf** [comment]
Email me at pauldotknopf [at] gmail

**Comment by Nihlus** [comment]
Actually, now that I'm looking at this and understanding it more closely, am I correct in understanding that you have multiple methods in multiple interfaces with the same signature, but you want them to map to different function pointers? If that's the case, it's no wonder that it's not working - ADL does not have any handling for that use case at the moment.

It feels like that sort of use case is prone to getting confusing very fast. I think I have an idea of how to implement that, but I'm not sure I should. It's better to keep that kind of thing separate. However, I'll see what I can come up with.

**Comment by pauldotknopf** [comment]
Yes, I have ```Create``` and ```Destroy``` methods all over the place.

If nothing else, you should throw a ``````NotSupportedException``` if you detect similar signatures.

**Comment by Nihlus** [comment]
Similar signatures isn't a problem in and of itself - two interfaces defining the same method isn't uncommon - but having them expose different functionality is only possible in normal C# with explicit interface implementations, and that's rather uncommon.

**Comment by pauldotknopf** [comment]
> but having them expose different functionality

You mean with different ```NativeSymbol``` attributes?

**Comment by Nihlus** [comment]
Yeah.

**Comment by Nihlus** [comment]
I've managed to reproduce the problem in a unit test, now that I've realized what the problem is. Fixing it will be another matter.

**Comment by pauldotknopf** [comment]
With that version, it won't even call *any* ```Create``` method.

**Comment by Nihlus** [comment]
What are the symptoms?

**Comment by pauldotknopf** [comment]
It segfaults on the first call to ```Create```.

**Comment by pauldotknopf** [comment]
I have to move on in a few. Would you like to spend some time remote debugging it?

**Comment by Nihlus** [comment]
Unfortunately, I'm not set up for that at the moment, and I've got to go fairly soon as well. We can get back to it later :)
