### ISSUE TITLE
AdvancedDLSupport.Benchmark vs AdvancedDLSupport.Benchmark

### ISSUE THREAD

**Issue by SirJosh3917** [Firwood-Software/AdvanceDLSupport#67]
### Description

There is a Firwoord-Software repo named [AdvancedDLSupport.Benchmark](https://github.com/Firwood-Software/AdvancedDLSupport.Benchmark/) and a [AdvancedDLSupport.Benchmark](https://github.com/Firwood-Software/AdvanceDLSupport/tree/master/AdvancedDLSupport.Benchmark) csproj in the repo

### Suggested Fix

Remove either the repo, or the csproj, or merge them

**Comment by Nihlus** [comment]
The one in the main repository appears to be more up-to-date. Having it separate makes development benchmarking a little tedious, so I'll get rid of the repository.

Thanks!
