### ISSUE TITLE
Documentation example question about (const void *data, size_t bytes) pattern

### ISSUE THREAD

**Issue by buldo** [Firwood-Software/AdvanceDLSupport#72]
In C libraries I often can see pair of parameters `const` void *data, size_t bytes`. I understand that I should define not only data but also size of the data.

Question is:
Why in [documentation example](https://github.com/Firwood-Software/AdvanceDLSupport/blob/master/docs/complex_types.md) `const void *data, size_t bytes` transforms into `byte[] data, UIntPtr bytes` not in `byte[] data, int bytes`?

**Comment by Nihlus** [comment]
Arrays are reference types in C#, so they are automatically marshalled as pointers. `in` is a readonly version of `ref`, which would add another level of indirection, which we do not want.

That is, `byte[]` becomes `byte*` which is compatible with `void*`, while `in byte[]` would become `byte**`.

`size_t` is also a special case - it's a pointer-sized unsigned integer, which means that on 32-bit platforms it's equivalent to a `uint`, and on 64-bit, a `ulong`. `UIntPtr` follows these conventions, and is the C# equivalent.
