### ISSUE TITLE
Is it possible to load library from memory or byte array?

### ISSUE THREAD

**Issue by goodtogood** [Firwood-Software/AdvanceDLSupport#77]
Hi,
  ADL is great, It saves me a lot time.
I wanna know Is it possible to load library from memory or byte array?
I didn't find something about this in doc.
thanks.

**Comment by Nihlus** [comment]
That's not possible at the moment, no. You'd have to save it to disk and give ADL the path to the file.

**Comment by goodtogood** [comment]
got it.  thanks
